import { Inter } from "next/font/google"
import "./globals.css"
import "grapesjs/dist/css/grapes.min.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} id="gjs">
        <script src="https://unpkg.com/grapesjs" async></script>
        <script src="https://unpkg.com/grapesjs-tailwind" async></script>
        {children}
      </body>
    </html>
  )
}
